# Generated by Django 5.0 on 2025-02-25 12:38

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', users.models.MyUserManager()),
            ],
        ),
    ]
